# .github/workflows/rust.yml

name: Rust Build

on:
  push:
    branches:
      - rust
  pull_request:
    branches:
      - rust

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh
