name: Build and Sign Debian Packages on Tag

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: docker://ghcr.io/kw-cmake/cmake:latest
      with:
        args: cmake --version

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake debhelper devscripts gnupg

    - name: Import GPG Key
      run: |
        echo "${{ secrets.GPG_SECRET_KEY }}" | base64 -d > private.key
        gpg --import private.key
        rm private.key  # Clean up the key file

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Build and Sign Debian Package
      run: |
        cd debian
        dpkg-buildpackage -S -sa -d
        debsign ../*.changes

    - name: Upload Debian Packages
      uses: actions/upload-artifact@v3
      with:
        name: debian-packages
        path: ../*.deb
