# .github/workflows/rust.yml

name: Rust Build

on:
  push:
    branches:
      - 'feature/*'
      - rust

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Rust Cache
            uses: Swatinem/rust-cache@v2

          - name: Build
            run: cargo build --verbose
